module(name = "advent_of_code")

bazel_dep(name = "rules_python", version = "1.0.0")

python_version = "3.12"

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    is_default = True,
    # We can specify the exact version.
    python_version = python_version,
)

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    download_only = True,
    hub_name = "pypi",
    # We need to use the same version here as in the `python.toolchain` call.
    python_version = python_version,
    requirements_lock = "//:configuration/requirements_lock.txt",
)
use_repo(pip, "pypi")
