[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "advent-of-code"
dynamic = ["version"]
description = 'Repository for Advent of Code challenges.'
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
keywords = []
authors = [
  { name = "jude253" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "rich~=14.2.0",
  "numpy~=2.3.4",
  "pandas~=2.3.3",
]

[project.urls]
Documentation = "https://github.com/jude253/AdventOfCode#readme"
Issues = "https://github.com/jude253/AdventOfCode/issues"
Source = "https://github.com/jude253/AdventOfCode"

[tool.hatch.version]
path = "src/advent_of_code/__about__.py"

[tool.hatch.envs.default]
path = ".venv"
python = "pypy3.11"
extra-dependencies = [
  "mypy==1.18.2",
  "ruff==0.14.3",
  "pygame-ce~=2.5.6",
]

[tool.hatch.envs.default.scripts]
sync-venv = [
  "python -V"
]

format = [
  "ruff format {args:src/advent_of_code tests bin}",
  "ruff check {args:src/advent_of_code tests bin} --fix",
]

lint = "ruff check {args:src/advent_of_code tests bin}"
types = "mypy --install-types --non-interactive {args:src/advent_of_code tests bin}"
check = [
  "format",
  "lint",
  "types",
]

# `hatch run clean`
clean = [
  "rm -rf dist build .venv* .*_cache **/*__pycache__",
]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]


[tool.coverage.run]
source_pkgs = ["advent_of_code", "tests"]
branch = true
parallel = true
omit = [
  "src/advent_of_code/__about__.py",
]

[tool.coverage.paths]
advent_of_code = ["src/advent_of_code", "*/advent-of-code/src/advent_of_code"]
tests = ["tests", "*/advent-of-code/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
